apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
        - name: psql
          image: postgres:11.7
          ports:
            - containerPort: 5432
          env:  # TODO: Use configmap/secrets
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: POSTGRES_DB
              value: "db"

---
apiVersion: v1
kind: Service
metadata:
  name: psql
spec:
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: psql
